
quarkus.http.port=8080
quarkus.log.category."io.quarkus.vertx.core.runtime.VertxCoreRecorder".level=OFF

quarkus.security.deny-unannotated-for-microprofile-jwt=false

# 2. C\u1ea5u h\u00ecnh B\u1ecf qua Auth cho ti\u1ec1n t\u1ed1 /qn v\u00e0 c\u00e1c file static
quarkus.http.auth.permission.public-ui.paths=/*
quarkus.http.auth.permission.public-ui.policy=permit


# Cho ph\u00e9p g\u1eedi/nh\u1eadn Cookie cross-origin
quarkus.http.cors.credentials=true

#quarkus.http.root-path=/api

smallrye.jwt.path.groups=groups

quarkus.smallrye-jwt.enabled=true

quarkus.log.category."io.quarkus.security".level=DEBUG
quarkus.log.category."io.smallrye.jwt".level=DEBUG
quarkus.log.category."org.jose4j".level=DEBUG
quarkus.log.category."io.agroal".level=DEBUG

# --- Database connection ---
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME:laravel}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD:secret}
quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL:jdbc:postgresql://localhost:5432/ke_toan}

quarkus.flyway.migrate-at-start=true
quarkus.hibernate-orm.database.generation=none


# --- Connection pool (Agroal) ---
quarkus.datasource.jdbc.min-size=2
quarkus.datasource.jdbc.max-size=10
quarkus.datasource.jdbc.acquisition-timeout=5S

# =========================
# Quinoa / React / Vite
# =========================

# Quinoa
#quarkus.quinoa.ui-dir=webgui
quarkus.quinoa.dev-server.enabled=true
quarkus.quinoa.dev-server.port=5173
quarkus.quinoa.build-dir=dist
quarkus.quinoa.enable-spa-routing=true

# CORS
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:8080,http://localhost:5173
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.credentials=true