quarkus.http.encoding=true
quarkus.http.charset=UTF-8

#smallrye.jwt.sign.key-location=secretKey.jwk
#mp.jwt.verify.publickey.location=secretKey.jwk
#smallrye.jwt.verify.key.location=secretKey.jwk
# smallrye.jwt.verify.key=eyJrdHkiOiJvY3QiLCJrIjoiYlhsemRYQmxjbXh2Ym1kelpXTnlaWFJyWlhsbWIzSm9jekkxTm1wM2RERXlNelExTmpjNE9UQSIsImFsZyI6IkhTMjU2In0
#smallrye.jwt.verify.algorithm=HS256
#mp.jwt.verify.issuer=ketoan-app

#mp.jwt.token.header=Cookie
#mp.jwt.token.cookie=jwt

smallrye.jwt.path.groups=groups

quarkus.smallrye-jwt.enabled=true

quarkus.log.category."io.quarkus.security".level=DEBUG
quarkus.log.category."io.smallrye.jwt".level=DEBUG
quarkus.log.category."org.jose4j".level=DEBUG
quarkus.log.category."io.agroal".level=DEBUG

# --- Database connection ---
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME:laravel}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD:secret}
quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL:jdbc:postgresql://postgres:5432/ke_toan}


# --- Connection pool (Agroal) ---
quarkus.datasource.jdbc.min-size=2
quarkus.datasource.jdbc.max-size=10
quarkus.datasource.jdbc.acquisition-timeout=5S

