quarkus.http.encoding=true
quarkus.http.charset=UTF-8

#quarkus.quinoa.ui-dir=src/main/webui
quarkus.quinoa.enable=true
quarkus.quinoa.install=false

# 1. \u0110\u01b0\u1eddng d\u1eabn g\u1ed1c c\u1ee7a Quinoa UI
#quarkus.quinoa.ui-root-path=/qn

# 2. B\u1eadt SPA Routing (b\u1eaft bu\u1ed9c \u0111\u1ec3 kh\u00f4ng b\u1ecb 404 khi v\u00e0o route con)
quarkus.quinoa.enable-spa-routing=true

# 3. Ch\u1ec9 \u0111\u1ecbnh ch\u00ednh x\u00e1c file index ch\u00ednh
quarkus.quinoa.index-page=index.html
quarkus.quinoa.build-dir=dist
quarkus.quinoa=true
#quarkus.quinoa.dev-server.port=5173
quarkus.http.port=8080
quarkus.log.category."io.quarkus.vertx.core.runtime.VertxCoreRecorder".level=OFF

quarkus.security.deny-unannotated-for-microprofile-jwt=false

# 2. C\u1ea5u h\u00ecnh B\u1ecf qua Auth cho ti\u1ec1n t\u1ed1 /qn v\u00e0 c\u00e1c file static
quarkus.http.auth.permission.public-ui.paths=/*
quarkus.http.auth.permission.public-ui.policy=permit

#smallrye.jwt.sign.key-location=secretKey.jwk
#mp.jwt.verify.publickey.location=secretKey.jwk
#smallrye.jwt.verify.key.location=secretKey.jwk
# smallrye.jwt.verify.key=eyJrdHkiOiJvY3QiLCJrIjoiYlhsemRYQmxjbXh2Ym1kelpXTnlaWFJyWlhsbWIzSm9jekkxTm1wM2RERXlNelExTmpjNE9UQSIsImFsZyI6IkhTMjU2In0
#smallrye.jwt.verify.algorithm=HS256
#mp.jwt.verify.issuer=ketoan-app

#mp.jwt.token.header=Cookie
#mp.jwt.token.cookie=jwt

smallrye.jwt.path.groups=groups

quarkus.smallrye-jwt.enabled=true

quarkus.log.category."io.quarkus.security".level=DEBUG
quarkus.log.category."io.smallrye.jwt".level=DEBUG
quarkus.log.category."org.jose4j".level=DEBUG
quarkus.log.category."io.agroal".level=DEBUG

# --- Database connection ---
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME:laravel}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD:secret}
quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL:jdbc:postgresql://localhost:5432/ke_toan}
quarkus.flyway.migrate-at-start=true
quarkus.hibernate-orm.database.generation=none


# --- Connection pool (Agroal) ---
quarkus.datasource.jdbc.min-size=2
quarkus.datasource.jdbc.max-size=10
quarkus.datasource.jdbc.acquisition-timeout=5S

